name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  # Backend job
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@4 # version 4.0.0 Nov 29, 2023
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Run Maven Tests
        working-directory: ./
        run: mvn clean test

